// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  session_server

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( SessionManager ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SessionManager ) UnmarshalJSON([]byte) error { return nil }
func ( SessionManager ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SessionManager ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SessionManager *SessionManager
